### ISSUE TITLE
Ugly error message when trying to save a read-only file

### ISSUE THREAD

**Issue by RWeigelt** [dvcrn/markright#31]
If I try to save a file that is read-only on disk (tested on Windows 10), I get an ugly error dialog:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EPERM: operation not permitted, open 'C:\TFS\_Current\Horizon\_Documentation\Test.md'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.writeFileSync (fs.js:1171:15)
    at Object.markright.main.write_file_BANG_ (C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:2650:415)
    at C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:2675:258
    at d (C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:2672:382)
    at b (C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:2673:330)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine (C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:1947:333)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped (C:\Program Files (x86)\MarkRight\resources\app.asar\app.js:1948:116)

[OK]
```

This error situation should be handled in a more end-user-friendly dialog (something like "File could not be saved because it is write-protected.").

**Comment by dvcrn** [comment]
A little more friendly but still room for improvements:

![screen shot 2015-11-16 at 2 39 32 pm](https://cloud.githubusercontent.com/assets/688326/11174989/ea4c649a-8c6f-11e5-8bdc-86c5a5b845d9.png)
