### ISSUE TITLE
Add 'open with' support (+ drag into the editor on mac)

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/markright#6]

**Comment by GeorgeHahn** [comment]
Drag into the editor would be pretty awesome on Windows too!

**Comment by dvcrn** [comment]
@GeorgeHahn I don't have a windows machine to test with, but the way I understood it is, that this should work on all systems the same. 
Please feel free to build it yourself and give it a try!

**Comment by flxfxp** [comment]
0.1.8 is giving errors:

```
Uncaught Exception:
TypeError: Cannot read property 'send' of null
    at BrowserWindow.send (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/atom.asar/browser/api/lib/browser-window.js:125:28)
    at Object.electron.ipc.cast (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:2323:39)
    at Object.markright.main.load_file_BANG_ (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:2658:64)
    at /opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:2714:54
    at d (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:2712:190)
    at b (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:2713:150)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:1947:333)
    at Object.cljs.core.async.impl.ioc_helpers.run_state_machine_wrapped (/opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:1948:116)
    at /opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:1949:321
    at /opt/homebrew-cask/Caskroom/markright/0.1.8/MarkRight.app/Contents/Resources/app.asar/app.js:1918:470
```

**Comment by dvcrn** [comment]
@flxfxp this is fixed in latest develop, but 'open with' when the app is not running yet still doesn't work (yet). 

The problem here is that the IPC system we implemented is trying to send the loaded content to the frontend (the receiving end) which isn't loaded yet. We probably need to re-design our IPC implementation a little bit.

**Comment by dvcrn** [comment]
All right, finally got this puppy resolved. If there are any issues with this, please let me know. I did some extensive tests before I filed the release but you know, things can happen.
